.TH log_enum 1 "27 AUG 2024" "0.10.1" 

.SH NAME
.B log_enum

.SH SYNOPSIS
.B log_enum
.RB [OPTIONS]

.SH DESCRIPTION
.B A small demo of using the Log Level Enum as an Option.
.SH ARGUMENTS
.SS OPTIONS
.B log_level:
[-null,--log-level "log_level_val (log.Level)"]:
  An Option using the `log.Level` Enum.


.SH AUTHOR
.B 00JCIV00

.SH COPYRIGHT
.B MIT License
