#! /usr/bin/env bash

# This Tab Completion script was generated by the Cova Library.
# Details at https://github.com/00JCIV00/cova


_covademo_completions() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD - 1]}"

    case "${prev}" in
        sub-cmd)
            _covademo_sub-cmd_completions
            ;;
        basic)
            _covademo_basic_completions
            ;;
        struct-cmd)
            _covademo_struct-cmd_completions
            ;;
        union-cmd)
            _covademo_union-cmd_completions
            ;;
        fn-cmd)
            _covademo_fn-cmd_completions
            ;;
        add-user)
            _covademo_add-user_completions
            ;;
        *)
            COMPREPLY=($(compgen -W "sub-cmd basic struct-cmd union-cmd fn-cmd add-user help usage" -- ${cur}))
    esac
}

_covademo_sub-cmd_completions() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD - 1]}"

    case "${prev}" in
        *)
            COMPREPLY=($(compgen -W "help usage" -- ${cur}))
    esac
}

_covademo_basic_completions() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD - 1]}"

    case "${prev}" in
        *)
            COMPREPLY=($(compgen -W "help usage" -- ${cur}))
    esac
}

_covademo_struct-cmd_completions() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD - 1]}"

    case "${prev}" in
        inner-cmd)
            _covademostruct-cmd_inner-cmd_completions
            ;;
        *)
            COMPREPLY=($(compgen -W "inner-cmd help usage" -- ${cur}))
    esac
}

_covademo_struct-cmd_inner-cmd_completions() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD - 1]}"

    case "${prev}" in
        *)
            COMPREPLY=($(compgen -W "help usage" -- ${cur}))
    esac
}

_covademo_union-cmd_completions() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD - 1]}"

    case "${prev}" in
        *)
            COMPREPLY=($(compgen -W "help usage" -- ${cur}))
    esac
}

_covademo_fn-cmd_completions() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD - 1]}"

    case "${prev}" in
        *)
            COMPREPLY=($(compgen -W "help usage" -- ${cur}))
    esac
}

_covademo_add-user_completions() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD - 1]}"

    case "${prev}" in
        *)
            COMPREPLY=($(compgen -W "help usage" -- ${cur}))
    esac
}


complete -F _covademo_completions covademo
