.TH basic-app-list-filter 1 "23 OCT 2024" "0.10.2" 

.SH NAME
.B basic-app-list-filter

.SH SYNOPSIS
.B basic-app-list-filter
.RB [OPTIONS]

.SH DESCRIPTION
.B List all current users matching the provided filter. Filters can be exactly ONE of any user field.
.SH ARGUMENTS
.SS OPTIONS
.B id:
[-i,--id "id (u16)"]:
  The 'id' Option.

.B admin:
[-a,--admin "admin (bool)"]:
  The 'admin' Option.

.B age:
[-A,--age "age (u8)"]:
  The 'age' Option.

.B first-name:
[-f,--first-name "first-name ([]const u8)"]:
  The 'first-name' Option.

.B last-name:
[-l,--last-name "last-name ([]const u8)"]:
  The 'last-name' Option.

.B phone:
[-p,--phone "phone ([]const u8)"]:
  The 'phone' Option.

.B address:
[-d,--address "address ([]const u8)"]:
  The 'address' Option.


.SH AUTHOR
.B 00JCIV00

.SH COPYRIGHT
.B MIT License
