.TH basic-app-list 1 "06 APR 2024" "0.10.0" 

.SH NAME
.B basic-app-list

.SH SYNOPSIS
.B basic-app-list
.RB [COMMAND]
.RB [OPTIONS]
.RB [VALUES]

.SH DESCRIPTION
.B List all current users.
.SH ARGUMENTS
.SS COMMANDS
.B filter:
List all current users matching the provided filter. Filters can be exactly ONE of any user field.


.SH AUTHOR
.B 00JCIV00

.SH COPYRIGHT
.B MIT License
