.TH basic-app-clean 1 "06 APR 2024" "0.10.0" 

.SH NAME
.B basic-app-clean

.SH SYNOPSIS
.B basic-app-clean
.RB [COMMAND]
.RB [OPTIONS]
.RB [VALUES]

.SH DESCRIPTION
.B Clean (delete) the default users file (users.csv) and persistent variable file (.ba_persist).
.SH ARGUMENTS
.SS OPTIONS
.B clean_file:
[-f,--file "clean_file (filepath)"]:
  Specify a single file to be cleaned (deleted) instead of the defaults.

.SH Examples

.B basic-app clean

.B basic-app delete --file users.csv



.SH AUTHOR
.B 00JCIV00

.SH COPYRIGHT
.B MIT License
