.TH basic-app 1 "23 OCT 2024" "0.10.2" 

.SH NAME
.B basic-app

.SH SYNOPSIS
.B basic-app
.RB [SUB COMMAND...]

.SH DESCRIPTION
.B A basic user management application designed to highlight key features of the Cova library.
.SH ARGUMENTS
.SS COMMANDS
.B new:
Add a new user.

.B open:
Open or create a users file.

.B list:
List all current users.

.B clean:
Clean (delete) the default users file (users.csv) and persistent variable file (.ba_persist).

.B view-lists:
View all lists (csv files) in the current directory.


.SH AUTHOR
.B 00JCIV00

.SH COPYRIGHT
.B MIT License
