# Requires PowerShell v5.1+

# This Tab Completion script was generated by the Cova Library.
# Details at https://github.com/00JCIV00/cova


# PowerShell Completion Installation Instructions for covademo
# 1. Load the completion script into your current PowerShell session:
#    . .\covademo-completion.ps1
#
# 2. Ensure your Execution Policy allows the script to be run. Example:
#    Set-ExecutionPolicy RemoteSigned
#
# 3. To ensure this completion script is loaded automatically in future sessions,
#    add the above sourcing command to your PowerShell profile:
#    Notepad $PROFILE
#    Add the line: . C:\path\to\covademo-completion.ps1
#
# 4. Restart your PowerShell session or source your profile again:
#    . $PROFILE


function _covademo {
    param($wordToComplete, $commandAst)
    $suggestions = @(
		'sub-cmd',
		'basic',
		'nest-1',
		'struct-cmd',
		'union-cmd',
		'fn-cmd',
		'add-user',
		'help',
		'usage',
		'--string',
		'--int',
		'--float',
		'--file',
		'--ordinal',
		'--cardinal',
		'--toggle',
		'--bool',
		'--verbosity',
		'--help',
		'--usage'
	)
    return $suggestions | Where-Object { $_ -like "$wordToComplete*" }
}

function _covademo-sub-cmd {
    param($wordToComplete, $commandAst)
    $suggestions = @(
		'help',
		'usage',
		'--nested_int',
		'--nested_str',
		'--help',
		'--usage'
	)
    return $suggestions | Where-Object { $_ -like "$wordToComplete*" }
}

function _covademo-basic {
    param($wordToComplete, $commandAst)
    $suggestions = @(
		'help',
		'usage',
		'--help',
		'--usage'
	)
    return $suggestions | Where-Object { $_ -like "$wordToComplete*" }
}

function _covademo-nest-1 {
    param($wordToComplete, $commandAst)
    $suggestions = @(
		'nest-2',
		'help',
		'usage',
		'--help',
		'--usage'
	)
    return $suggestions | Where-Object { $_ -like "$wordToComplete*" }
}

function _covademo-nest-1-nest-2 {
    param($wordToComplete, $commandAst)
    $suggestions = @(
		'nest-3',
		'help',
		'usage',
		'--help',
		'--usage'
	)
    return $suggestions | Where-Object { $_ -like "$wordToComplete*" }
}

function _covademo-nest-1-nest-2-nest-3 {
    param($wordToComplete, $commandAst)
    $suggestions = @(
		'nest-4',
		'help',
		'usage',
		'--inheritable',
		'--help',
		'--usage'
	)
    return $suggestions | Where-Object { $_ -like "$wordToComplete*" }
}

function _covademo-nest-1-nest-2-nest-3-nest-4 {
    param($wordToComplete, $commandAst)
    $suggestions = @(
		'help',
		'usage',
		'--help',
		'--usage'
	)
    return $suggestions | Where-Object { $_ -like "$wordToComplete*" }
}

function _covademo-struct-cmd {
    param($wordToComplete, $commandAst)
    $suggestions = @(
		'inner-cmd',
		'help',
		'usage',
		'--int',
		'--str',
		'--str2',
		'--flt',
		'--int2',
		'--multi-int',
		'--multi-str',
		'--rgb-enum',
		'--struct-bool',
		'--struct-str',
		'--struct-int',
		'--help',
		'--usage'
	)
    return $suggestions | Where-Object { $_ -like "$wordToComplete*" }
}

function _covademo-struct-cmd-inner-cmd {
    param($wordToComplete, $commandAst)
    $suggestions = @(
		'help',
		'usage',
		'--in-bool',
		'--in-float',
		'--help',
		'--usage'
	)
    return $suggestions | Where-Object { $_ -like "$wordToComplete*" }
}

function _covademo-union-cmd {
    param($wordToComplete, $commandAst)
    $suggestions = @(
		'help',
		'usage',
		'--int',
		'--str',
		'--help',
		'--usage'
	)
    return $suggestions | Where-Object { $_ -like "$wordToComplete*" }
}

function _covademo-fn-cmd {
    param($wordToComplete, $commandAst)
    $suggestions = @(
		'help',
		'usage',
		'--help',
		'--usage'
	)
    return $suggestions | Where-Object { $_ -like "$wordToComplete*" }
}

function _covademo-add-user {
    param($wordToComplete, $commandAst)
    $suggestions = @(
		'help',
		'usage',
		'--fname',
		'--lname',
		'--age',
		'--admin',
		'--ref-ids',
		'--help',
		'--usage'
	)
    return $suggestions | Where-Object { $_ -like "$wordToComplete*" }
}

Register-ArgumentCompleter -CommandName 'covademo.exe' -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPos)

    $functionName = "_" + $($commandAst.Extent.Text.replace(' ', '-').replace(".exe", ""))
    if ($wordToComplete) {
        $functionName = $functionName.replace("-$wordToComplete", "")
    }

    # Check if the function exists and invoke it
    if (Get-Command -Name $functionName -ErrorAction SilentlyContinue) {
        & $functionName $wordToComplete $commandAst
    } else {
        # Fallback logic to show files in the current directory
        Get-ChildItem -Path '.' -File | Where-Object Name -like "*$wordToComplete*" | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_.Name, $_.Name, 'ParameterValue', $_.Name)
        }
    }
}