.TH logger 1 "23 OCT 2024" "0.10.2" 

.SH NAME
.B logger

.SH SYNOPSIS
.B logger
.RB [OPTIONS]

.SH DESCRIPTION
.B A small demo of using the Log Level Enum as an Option.
.SH ARGUMENTS
.SS OPTIONS
.B log_level:
[-null,--log-level "log_level_val (log.Level)"]:
  An Option using the `log.Level` Enum.


.SH AUTHOR
.B 00JCIV00

.SH COPYRIGHT
.B MIT License
