#! /usr/bin/env bash

# This Tab Completion script was generated by the Cova Library.
# Details at https://github.com/00JCIV00/cova


# Bash Completion Installation Instructions for log_enum
# 1. Place this script in a directory like /etc/bash_completion.d/ (Linux)
#    or /usr/local/etc/bash_completion.d/ (Mac, if using Homebrew and bash-completion)
#
# 2. Ensure the script has executable permissions:
#    chmod +x log_enum-completion.bash
#
# 3. Source this script from your .bashrc or .bash_profile by adding:
#    . /path/to/log_enum-completion.bash
#
# 4. Restart your terminal session or source your profile again:
#    source ~/.bashrc  # or ~/.bash_profile


_log_enum_completions() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD - 1]}"

    case "${prev}" in
        "log_enum")
            COMPREPLY=($(compgen -W "help usage --log-level --help --usage" -- ${cur}))
            ;;
        *)
            COMPREPLY=($(compgen -f -- ${cur}))
    esac
}


complete -F _log_enum_completions log_enum