.TH covademo-struct-cmd 1 "23 OCT 2024" "0.10.2" 

.SH NAME
.B covademo-struct-cmd

.SH SYNOPSIS
.B covademo-struct-cmd
.RB [OPTIONS]
.RB [VALUES]
.RB [SUB COMMAND...]

.SH DESCRIPTION
.B A demo sub command made from a struct.
.SH ARGUMENTS
.SS COMMANDS
.B inner-cmd:
An inner/nested command for struct-cmd

.SS OPTIONS
.B int:
[-i,--int "int (i32)"]:
  The first Integer Value for the struct-cmd.

.B str:
[-s,--str "str (text)"]:
  The 'str' Option.

.B str2:
[-S,--str2 "str2 (text)"]:
  The 'str2' Option.

.B flt:
[-f,--flt "flt (f16)"]:
  The 'flt' Option.

.B int2:
[-I,--int2 "int2 (u16)"]:
  The 'int2' Option.

.B multi-int:
[-m,--multi-int "multi-int (u8)"]:
  The 'multi-int' Value.

.B multi-str:
[-M,--multi-str "multi-str (text)"]:
  The 'multi-str' Value.

.B rgb-enum:
[-r,--rgb-enum "rgb-enum (covademo.DemoStruct.InnerEnum)"]:
  The 'rgb-enum' Option.

.B struct-bool:
[-t,--struct-bool "struct-bool (toggle)"]:
  The 'struct_bool' Option of type 'toggle'.

.B struct-str:
[-T,--struct-str "struct-str (text)"]:
  The 'struct_str' Option of type 'text'.

.B struct-int:
[-R,--struct-int "struct-int (i64)"]:
  The 'struct_int' Option of type 'i64'.

.SS VALUES
.B multi-int-val:
(u16): The 'multi-int-val' Value.


.SH AUTHOR
.B 00JCIV00

.SH COPYRIGHT
.B MIT License
