.TH covademo-fn-cmd 1 "23 OCT 2024" "0.10.2" 

.SH NAME
.B covademo-fn-cmd

.SH SYNOPSIS
.B covademo-fn-cmd
.RB [VALUES]

.SH DESCRIPTION
.B A demo sub command made from a function.
.SH ARGUMENTS
.SS VALUES
.B int:
(i32): The first Integer Value for the fn-cmd.

.B string:
(text): The first String Value for the fn-cmd.

.B byte_array:
(u8): A 6-Byte Array for fn-cmd


.SH AUTHOR
.B 00JCIV00

.SH COPYRIGHT
.B MIT License
