.TH covademo-struct-cmd-inner-cmd 1 "06 APR 2024" "0.10.0" 

.SH NAME
.B covademo-struct-cmd-inner-cmd

.SH SYNOPSIS
.B covademo-struct-cmd-inner-cmd
.RB [COMMAND]
.RB [OPTIONS]
.RB [VALUES]

.SH DESCRIPTION
.B An inner/nested command for struct-cmd
.SH ARGUMENTS
.SS OPTIONS
.B in-bool:
[-null,--in-bool "in-bool (bool)"]:
  The 'in_bool' Option of type 'bool'.

.B in-float:
[-null,--in-float "in-float (f32)"]:
  The 'in_float' Option of type 'f32'.


.SH AUTHOR
.B 00JCIV00

.SH COPYRIGHT
.B MIT License
