.TH covademo-union-cmd 1 "23 OCT 2024" "0.10.2" 

.SH NAME
.B covademo-union-cmd

.SH SYNOPSIS
.B covademo-union-cmd
.RB [OPTIONS]
.RB [VALUES]

.SH DESCRIPTION
.B A demo sub command made from a union.
.SH ARGUMENTS
.SS OPTIONS
.B int:
[-i,--int "int (i32)"]:
  The first Integer Value for the union-cmd.

.B str:
[-s,--str "str (text)"]:
  The first String Value for the union-cmd.

.SS VALUES
.B union-uint:
(u8): The 'union-uint' Value.

.B union-str:
(text): The 'union-str' Value.


.SH AUTHOR
.B 00JCIV00

.SH COPYRIGHT
.B MIT License
