.TH covademo-add-user 1 "23 OCT 2024" "0.10.2" 

.SH NAME
.B covademo-add-user

.SH SYNOPSIS
.B covademo-add-user
.RB [OPTIONS]
.RB [VALUES]

.SH DESCRIPTION
.B A demo sub command for adding a user.
.SH ARGUMENTS
.SS OPTIONS
.B fname:
[-f,--fname "fname (text)"]:
  The 'fname' Option.

.B lname:
[-l,--lname "lname (text)"]:
  The 'lname' Option.

.B age:
[-a,--age "age (u8)"]:
  The 'age' Option.

.B admin:
[-A,--admin "admin (toggle)"]:
  The 'admin' Option.

.B ref-ids:
[-r,--ref-ids "ref-ids (u8)"]:
  The 'ref-ids' Value.

.SS VALUES
.B id:
(u16): The 'id' Value.


.SH AUTHOR
.B 00JCIV00

.SH COPYRIGHT
.B MIT License
